spring:
  application:
    name: green-service
  
  cloud:
    consul:
      port: 8500
      discovery:
        instance-id: ${spring.application.name}.${random.value}
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 0
  

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

logging:
  file:
    name: /var/tmp/logs/green-service/green-service
  level:
    root: info
    poc.springcloud: debug  
